logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

spring:
  profiles:
    active: dev

server:
  servlet:
    context-path: "/api/v1"

application.jwt.secretKey: jwtsecretkeyjwtsecretkey
application.jwt.validityPeriod: 86400000

application.fixerApi.accessKey: 3141832914157c531df042d0c15401f9
application.fixerApi.baseUrl: http://data.fixer.io/api