#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG


spring:
  profiles:
    active: dev
  datasource:
    initialization-mode: always
    continue-on-error: true

server:
  servlet:
    context-path: "/api/v1"

application.jwt.secretKey: jwtsecretkeyjwtsecretkey
application.jwt.validityPeriod: 86400000

application.currencyApi.accessKey: bf6095f2b7454be1ac2d
application.currencyApi.baseUrl: https://free.currconv.com/api/v7