spring:
  datasource:
    url: jdbc:mysql://localhost:3306/currencyconverter_db?serverTimezone=Africa/Lagos
    username: root
    password: vikkidchamp
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    hibernate:
      ddl-auto: update